### ISSUE TITLE
Option to set the delay between opening tabs.

### ISSUE THREAD

**Issue by zoocey** [cpriest/SnapLinksPlus#153] opened 2016-12-09 12:02 UTC
As above would like an option like "Delay between actions (in miliseconds)" from v2 that delays the opening of tabs and doesn't load them all ASAP. 

A few sites I visit have some sort of robot/spidering detection that gets triggered by opening a bunch of links rapidly. The delay option made these sites work without issue.

**Comment by Keith94** [comment] 2016-12-09 14:47
Dupe of #114

**Closed** 2016-12-09 15:17 UTC
