### ISSUE TITLE
Two bugs with latest commit

### ISSUE THREAD

**Issue by Phyxion** [cpriest/SnapLinksPlus#117] opened 2016-10-20 09:02 UTC
- Interestingly, on the [welcome](http://cpriest.github.io/SnapLinksPlus/welcome.html) page as-is, the rectangles aren't drawn correctly over the links and also both scrollbars appear (it does not without right-clicking).
- I also noticed that with the last version if you drag with right mouse button, don't select anything, and then let go of the right mouse button AND then drag again that there is no selection rectangle anymore.

**Comment by cpriest** [comment] 2016-10-22 22:59
Hmm, that may be due to the quick fix I made w/ the rectangle showing up (without a drag) on initial use.  I'll push out anything I have locally in a bit and see if it still happens.

**Comment by Phyxion** [comment] 2016-10-23 12:20
Alright, sounds great. If it's there I can always test it out 👍

**Comment by cpriest** [comment] 2016-10-26 21:52
I didn't have anything additional to push out and sorry, been swamped with work and sick.  I'll try and pick this back up this weekend or next week.

**Comment by Phyxion** [comment] 2016-10-27 08:57
No problem, take your time, it works rather well as-is, just a few bugs left but it isn't that bad :)

**Comment by FatOrangutan** [comment] 2016-10-27 12:23
@Phyxion , could you upload an xpi for the latest version? I would like to try it but I don't know how to install add-ons from GitHub. I don't need the add-on to to be signed.
Thanks.

**Comment by Phyxion** [comment] 2016-10-27 12:38
If you download this repo and go to about:debugging you can load temp addon (select manifest.json). However, ideally you should sign the addon on Mozilla's website, as otherwise you'd have to install the addon every time you start Firefox again.

**Comment by cpriest** [comment] 2016-11-05 12:11
Hey Phyxion, just getting some time to put in on this.  I'm not seeing the first problem you mentioned here:

> Interestingly, on the welcome page as-is, the rectangles aren't drawn correctly over the links and also both scrollbars appear (it does not without right-clicking).

I see the other problem, working on the fix now.

**Comment by cpriest** [comment] 2016-11-05 12:58
@FatOrangutan I've built an .xpi of the soon to be released version, you can get it here: https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b1.xpi

**Comment by Phyxion** [comment] 2016-11-05 15:09
Here you can see that bug @cpriest  http://i.imgur.com/QIsouel.jpg

**Comment by cpriest** [comment] 2016-11-05 21:29
Thanks, that wasn't easy to reproduce, semi-strange.  Anyways, I saw what was causing it and did things a little differently.  Let me know if you see anything else weird happening as a result of the latest change.

To be more specific, the problem was the SVG overlay being as large as the document, which wasn't being updated when the document size changed.  I changed it to 100x100 with overflow visible which seems to work just fine.  

The oddity though is that it didn't work when I had it at 0x0 or even 5x5, it had other offset issues which doesn't make much sense to me.  I did test it with 100x100 on various browser window sizes, seems fine.

**Comment by cpriest** [comment] 2016-11-05 21:47
Actually some other unexpected things are happening, changing this a bit still.

**Comment by Phyxion** [comment] 2016-11-06 09:50
Alright, let me know when it's ready to test and I'll be more than happy to try it out 👍 
That bug happen(s)(ed) all the time on that page on my machine btw.

**Comment by cpriest** [comment] 2016-11-06 20:32
Working on a fix for that http://www.ldraw.org/cgi-bin/ptlist.cgi page which seems to be doing something very strange which causes the documentElement.scrollTop to never change...  Just that to figure out/fix, welcome page updates and then I think ready for .xpi testing for a release.

**Comment by cpriest** [comment] 2016-11-06 21:37
Alright, the latest commits/updates should take care of all outstanding items before release.  Care to test it out?  Both of the problems here should be fixed.  You and I are using the dev tree version, but I have packaged an XPI [here](https://github.com/cpriest/SnapLinksPlus/raw/master/dist/SnapLinks-3.1.0b2.xpi) if you want to try that, I'll be doing testing with that next, then maybe a release very soon, perhaps today.

**Comment by Phyxion** [comment] 2016-11-07 08:13
I'll test it out today, btw, your xpi won't sign:

    Your add-on failed validation with 2 errors.

    Cannot find min/max version. Maybe "strict_min_version" or "strict_max_version" contains an unsupported version?
    Invalid minimum version number

**Comment by Phyxion** [comment] 2016-11-07 08:19
- Welcome page is now working fine.
- Rectangle is now working if you press RMB twice.
- However, if you go to [this](http://www.nfohump.com/forum/) page, you'll get scrolled to the bottom (if you keep RMB pressed it remains stuck).
- I'll continue testing, if I find another bug I'll let you know 👍

**Comment by cpriest** [comment] 2016-11-07 12:31
Hmm, on that #3, what steps are you doing exactly that cause the issue?

**Comment by Phyxion** [comment] 2016-11-07 12:33
Just clicking right mouse button, it immediately scrolls the page to the bottom.

**Comment by cpriest** [comment] 2016-11-07 12:33
ok, I'll check it out this evening.

**Comment by cpriest** [comment] 2016-11-08 01:41
Hmm, on that #3, what steps are you doing exactly that cause the issue?

**Comment by cpriest** [comment] 2016-11-08 02:15
Sorry, was having a mail problem and my email just went through.

**Comment by Phyxion** [comment] 2016-11-08 10:00
No problem :) If you need help testing, just ask.

**Comment by cpriest** [comment] 2016-11-08 12:31
#3 has raised up a thorny issue, which is (in theory) resolved by this snippet from 2010, not enough time this morning to implement it, but will finish up as soon as I can (which should address this latest bug).

https://bugzilla.mozilla.org/show_bug.cgi?id=156388#c14

**Comment by cpriest** [comment] 2016-11-08 12:34
Could you test out the b2 xpi and see if #124 is happening?

If b2 works anywhere, could you test that xpi far and wide?  It should be good to go sans the remaining issues, unless what @sfinam is experiencing isn't isolated to his Ubuntu 16/FF49.

Thanks for all your help @Phyxion

**Comment by Phyxion** [comment] 2016-11-08 13:42
I don't use Linux, so I can't, unfortunately. The rest seems to work fine indeed, other than the scroll to bottom issue.

**Comment by cpriest** [comment] 2016-11-11 12:11
Alright, so that bullet point 3 should be fixed.  Since this is all in this one ticket (numerous issues), I'm not certain if there are any outstanding issues in here, I don't think there is.  I'm going to close this ticket, if there is a new issue lets start a new ticket.

**Closed by cpriest** 2016-11-11 12:11 UTC

**Comment by Phyxion** [comment] 2016-11-12 10:19
Agreed, just tested it and it works fine now, thanks for the fix 👍  If I find another bug I'll let you know but so far everything looks OK.
