### ISSUE TITLE
[Feature request] Copy links in custom format

### ISSUE THREAD

**Issue by ReporterX** [cpriest/SnapLinksPlus#273] opened 2019-04-09 21:30 UTC
I would like to copy both the link texts and the link urls.

For example
[Google!](http://google.com)

[Yahoo!](http://yahoo.com)

Drag and copy will produce this:
```
Google	http://google.com
Yahoo	http://yahoo.com
```
The custom format is:
`Link text<tab delimiter>Link URL`

The legacy "Multi Links Plus" has this feature.

**Comment by cpriest** [comment] 2019-04-10 12:54
Thanks, I'll look at doing something like this.

**Comment by remi-garcia** [comment] 2022-01-05 13:06
Either a duplicate of #198 or could be tackled by #409

**Closed by remi-garcia** 2022-01-05 13:06 UTC
Labels: enhancement, help wanted
