### ISSUE TITLE
Please give us ability to cancel or disable when using Mouse gestures

### ISSUE THREAD

**Issue by HillsCloud** [cpriest/SnapLinksPlus#204] opened 2017-11-26 18:35 UTC
I use Foxy gestures which also gets executed using right clicks. Snap links interferes  with this. Is it possible to make it compatible with Foxy gestures and can be done by following: 

1. Making snap links activate by drawing a circle.
2. Activate only when using contrl or alt key
3. Disable activation when pressed for more than 2 seconds. 
4. Activate only when drawing a circle instead of an automatic square that is being done now. 

Thanks for the addon.

**Comment by cpriest** [comment] 2017-11-27 17:47
Duplicate of #189

**Closed by cpriest** 2017-11-27 17:47 UTC
