### ISSUE TITLE
Opening 2 to 3 thosand links

### ISSUE THREAD

**Issue by ProximaNova** [cpriest/SnapLinksPlus#157] opened 2016-12-22 17:48 UTC
The older version had no issue opening 2 to 3 thousand links as it opened them 10 at a time for around 10 or 20 seconds but the new version opens them all at once and causes Firefox to become unresponsive.

**Comment by cpriest** [comment] 2016-12-22 23:47
Duplicate of #114 please search for an open issue before posting.

**Closed by cpriest** 2016-12-22 23:47 UTC
