### ISSUE TITLE
Broken spell check if no Start Selecting With modifier key selected

### ISSUE THREAD

**Issue by tgbugs** [cpriest/SnapLinksPlus#71] opened 2015-05-02 23:34 UTC
Repro: 
1. Set Start Selecting With to right mouse button with no modifier key.
2. Go to a text box and create a misspelled word.
3. Click the corrected version of the word.
4. Word is not corrected. On the right click menu corrections are added to the list again (and now appear on the right click menu in any context), the current dictionary is added to the list of dictionaries again.

**Comment by MarcoFalke** [comment] 2015-06-28 12:34
I can reproduce this.

**Comment by SvenPM** [comment] 2015-06-28 12:49
Should be a duplicate of https://github.com/cpriest/SnapLinksPlus/issues/64

**Closed** 2016-04-30 10:46 UTC
Labels: duplicate
