### ISSUE TITLE
Add config option to prevent the tutorial popup notification

### ISSUE THREAD

**Issue by dws14159** [cpriest/SnapLinksPlus#363] opened 2021-09-09 14:43 UTC
Don't need or want a tutorial, used the extension before. Want the tutorial popup to stop popping up.
It doesn't get the hint if I click on it a few times and use the extension a few times.
It doesn't get the hint if I explicitly close it a few times.
If I wait for it to go away of its own accord it hangs around for WAAAAY too long.
And it opens up EVERY TIME I start my browser.

So please add a config option to switch this annoying popup off.

**Comment by remi-garcia** [comment] 2021-09-09 15:03
I'm not sure that deserves a response. Yet here's one.

The popup should only open on updates. This is probably related to #358 (the add-on unexpectedly resets to default options for some reason).

Since @dws14159 missed the option he asks for... and this is a duplicate of #358 I'll close this non-issue.

**Closed by remi-garcia** 2021-09-09 15:03 UTC

**Comment by cpriest** [comment] 2021-09-09 15:17
In addition, the feature to turn off notifications is already present.  It is related to the recent bugs from the last 2 releases.  The next release (hopefully well tested) should be out very soon.
