### ISSUE TITLE
"Save Links" doesn't work

### ISSUE THREAD

**Issue by cpriest** [cpriest/SnapLinksPlus#36] opened 2014-02-04 15:42 UTC
Reported by guy.jh.marty, Nov 28, 2012

What steps will reproduce the problem?
1.Select links
2.Choose "Save link" (in French "Enregistrer les cibles des liens sous")
3.Nothing happend

What is the expected output? What do you see instead?
I expected that a popup open to choose the destination folder
Instead, nothing happend

What version of the product are you using? On what operating system?
Snalink plus 2.3.1
Firefox 17.0
MS Windows XP SO3

What is the page URL where this issue is occuring:
All pages

Today (14 hours ago) Delete comment
#2 itchybig

I'm having the same issue.

Snap Links Plus 2.4.0
Firefox 26.0
Windows XP SP3

Thanks.

**Comment by PelzaK** [comment] 2015-01-07 17:07
Not working for me too. I just want to download many files with no luck. FF34.

**Comment by remi-garcia** [comment] 2019-08-24 08:21
Duplicate of #33 since this is not a bug anymore but a new feature to add
Should be closed

**Closed** 2019-08-25 01:47 UTC
Labels: bug
