### ISSUE TITLE
Request: Support for touch interfaces

### ISSUE THREAD

**Issue by davidhedlund** [cpriest/SnapLinksPlus#215] opened 2018-01-28 15:56 UTC
https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/versions/ says
> Version 3.1.1.3 Released Dec. 20, 2016 69.2 KiB Works with Firefox for Android 50.0 and later, Firefox 50.0 and later
> Source code released under MIT/X11 License What's this?

The author [said](https://github.com/cpriest/SnapLinksPlus/issues/213#issuecomment-361068649):
> if you had some way of telling your android what a right click was then it would work just fine.  It's not specifically written to work with touch events.  If you want to open up a new ticket requesting support for touch interfaces, that would be good.

**Comment by remi-garcia** [comment] 2020-12-07 08:25
Duplicate of #310 - Closing this one

**Closed by remi-garcia** 2020-12-07 08:25 UTC
Labels: enhancement
