### ISSUE TITLE
Firefox slows to a CRAWL when this addon is enabled and I visit Tumblr

### ISSUE THREAD

**Issue by Lemons224** [cpriest/SnapLinksPlus#247] opened 2018-07-27 05:27 UTC
First off love this addon and it has served me quite well, but lately every time I open a Tumblr it feels like I'm back on dial-up connection because the page will load extremely slowly and nothing will even be clickable for around 20 seconds! It's been so bad it has even crashed my browser!

I finally got fed up with this behavior and disabled all my addons and re-enabled them one by one. Once they were all off Tumblr was loading fast again! I started to re-enable my addons and when I got to Snap Links BAM...back to extremely slow loading.

Same thing with Reddit's new layout...something about how those sites are designed is not mixing well with this addon....I will have to keep it disabled until these issues are fixed because it's simply unbearable. Please fix!

**Comment by cpriest** [comment] 2018-07-27 23:07
Hmm, does it do this with only Snap Links Plus enabled?

**Comment by cpriest** [comment] 2018-07-29 00:35
Strange, I could see it being very slow if it was still the old pre-web-extension version, if that even worked.

Glad that solved it.

**Comment by cpriest** [comment] 2018-08-03 11:52
I didn't see the update to the edit, was just looking for this ticket re: another ticket someone posted about Tumblr.  So this issue is still present even in a fresh profile and only Snap Links Plus installed?  Is this in FF or Chrome?  #231

**Comment by oddPT** [comment] 2018-09-17 18:42
Lemons224, try the version 3.1.2.3. It is the last one I dont have issues with.
You must disable the addons automatic updates.

**Comment by kulfoon** [comment] 2019-07-08 20:47
This is another trash-duplicate of https://github.com/cpriest/SnapLinksPlus/issues/231, can be closed as now that the original issue has been fixed.

**Comment by cpriest** [comment] 2019-07-08 21:46
Thanks for looking through them, appreciate it.  @Lemons224, if you still are experiencing this issue with 3.1.7 or higher, please comment on this ticket about it.

**Closed by cpriest** 2019-07-08 21:46 UTC
Labels: bug, needs triage
