### ISSUE TITLE
Feature Request: Tabs to Open at End 2

### ISSUE THREAD

**Issue by Xadeth** [cpriest/SnapLinksPlus#149] opened 2016-12-04 00:50 UTC
Hi cpriest,

The new Snap Links Plus changed to make tabs open next to the current tab instead of at the end. I noticed that there was a suggestion back in 2014 for the exact same request, but why has it been reverted? Is there a way for me to open the tabs at the end again? Will the next version with the configuration panel have this option back in?

Also, it would be great as well if it doesn't switch me to the new tab immediately, as I may have more links to open.

Original Issue: https://github.com/cpriest/SnapLinksPlus/issues/58

Thank you.

**Comment by btanner2** [comment] 2018-09-03 10:54
Is this issue probably a duplicate of https://github.com/cpriest/SnapLinksPlus/issues/193 ?

**Comment by cpriest** [comment] 2018-09-05 01:42
Yes, probably.

**Comment by cpriest** [comment] 2018-09-05 01:44
This is fixed in the upcoming release.

**Closed by cpriest** 2018-09-05 01:44 UTC
Labels: enhancement
