### ISSUE TITLE
Firefox with many tabs open will hang when enabling Snap Links Plus extension

### ISSUE THREAD

**Issue by caitmuenster** [cpriest/SnapLinksPlus#280] opened 2019-05-24 20:57 UTC
Hi Clint, I'm the Firefox Add-ons Community Manager. I recently saw a user [report a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1474807) for Snap Links Plus for Firefox on bugzilla.mozilla.org and wanted to pass along their report to you: 

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0
Build ID: 20180709172241

Steps to reproduce:

Open many tabs. Then install or enable (must be disabled beforehand) the Snap Links Plus extension.

Actual results:

Firefox will become unresponsive and hang for some time depending on how many tabs are open. This can be several minutes where the user is unable to interact with the browser.

Here is a performance profile I recorded using a new profile in nightly 63.0a1 (2018-07-10):
https://perfht.ml/2KNx0fi

For that recording I opened 42 tabs and then enabled Snap Links Plus.

Expected results:

Firefox should have continued to respond to user interaction at a reasonable pace.

**Comment by cpriest** [comment] 2019-05-25 17:03
Hmm, ok.  I'll look into it as soon as I can, thanks!

**Comment by cpriest** [comment] 2019-05-25 20:44
Hmm, that's a spiffy profile report.  I don't see any mention to calls in my extension though.  In looking at the current release code, I don't see anything I'm doing to cause a page reload on plugin activation.  

Is this simply the result of the loading the code from the extension into the page?

If you could point me at any resources for how I could effectively measure my extensions 'startup time' on a page load it would be much appreciated.  I have not reviewed it in a profiler but it has been specifically designed to do very little on load besides setting up some pub/sub channels and hooking onMouseDown.

**Comment by cpriest** [comment] 2019-05-25 22:01
Okay, actually I took another look at the profiler link you had.  I'm seeing it looks related to the Config.js broadcasting of the configuration, does that look right to you?

**Comment by cpriest** [comment] 2019-05-25 23:45
Alright, so I have gotten a profiler profile setup with just SnapLinks and the profiler.  I opened up 42 tabs of google.com while profiling it.

This is quite outside my own wholistic understanding, but from what I see from this published profiling: https://perfht.ml/2EwrVCE  Looking at one of the 'red bars' of a content process.  It shows 112ms event processing delay.  I believe the associated call graph shows only 9ms of that was SnapLinks.

Am I reading that wrong?  At no point during the profiling did Firefox become unresponsive at all.

**Comment by caitmuenster** [comment] 2019-05-28 18:02
Thanks for looking into this, @cpriest! I'm not sure. :/ We needinfo'd the reporter about a month ago and haven't heard a response. I'm happy to have this bug closed on Bugzilla as an INVALID or WONTFIX if it's not reproducible.

**Comment by cpriest** [comment] 2019-05-29 11:36
No problem, clearly I got further with the profiler on my own and I was 
able to identify what the problem is (I think), which I'm in the process 
of fixing up.  May take some time though, but it will probably be a new 
point release on its own as it will address a number of tickets without 
the kind of detail you had in your first link; which was of tremendous 
value once I understood how to use it and reproduce it on my own, so thanks!

**Comment by cpriest** [comment] 2019-07-01 11:45
Just an FYI, I've released 3.1.7 which should take care of this.  Some early testers have already reported major improvements in speed.  Closing this ticket but if you see any other issues please comment here.

**Closed by cpriest** 2019-07-01 11:45 UTC
