### ISSUE TITLE
not switching to next open tab

### ISSUE THREAD

**Issue by thaliel** [cpriest/SnapLinksPlus#220] opened 2018-03-06 14:11 UTC
The beta seems to have changed how tabs are handled. once you close the tab righ next to your "start tab" (the one where you selected all the links to be opened), you will be back at exactly that tab instead of being taking to the tab to the right

**Comment by cpriest** [comment] 2018-03-07 04:09
I don't know how that could possibly be, I haven't done anything that would do that or control that in any way.

How do tabs behave when Snap Links is not enabled?

**Comment by thaliel** [comment] 2018-03-07 04:15
the same way the do when I have 3.1.1.3 active: löet's say I have opened 3 tabs, tab 1 being the ,leftmost where I selected links. When I go to tab 2 and close it, you would normally have tab 3 become tab 3 and be the active tab next to tab 1. But with the beta active, closing tab 2 takes you back to tab 1

**Comment by cpriest** [comment] 2018-03-07 11:34
Okay, so I just tested this under 3 scenarios in FF Dev Edition.

1. With SnapLinks 3.2.1b1
2. With SnapLinks 3.1.1.3
3. Without any extensions enabled

In all 3 scenarios (whether the new tabs were opened from snap links for via ctrl-shift click a link), when the active tab is closed, the tab to the right activates.

This is the way FF behaves on its own, without any extensions and is also consistent with both versions of SnapLinks.

Can you record a quick video with 3.1.1.3 showing it acting differently?  Can you verify that without any other extensions running?

**Comment by thaliel** [comment] 2018-03-07 14:19
I recorded it on my phone, so qaulity is not the best. Here is how things look with gthe beta active:
https://www.4shared.com/video/bSzJueyoca/VID_20180307_1359022.html 

this is with deactivated addons (potected mode)
https://www.4shared.com/video/hRUC6y2xei/VID_20180307_1405351.html

This is on a clean profile 
https://www.4shared.com/video/BJTWrqRnca/VID_20180307_1409271.html

and finally, this is with 3.1.1.3 active
https://www.4shared.com/video/0bCfK8Fsca/VID_20180307_1411281.html

**Comment by cpriest** [comment] 2018-03-07 23:50
It doesn't seem to want to let me download those.  You can post them here by just dragging them to the comment box from your computer.  

What browser and version are you using?  I tested this and cannot reproduce the issue.

**Comment by thaliel** [comment] 2018-03-08 00:19
I am using the most recent version of firefox (58.0.2)
[https://www.4shared.com/video/bSzJueyoca/VID_20180307_1359022.html](url)

[https://www.4shared.com/video/hRUC6y2xei/VID_20180307_1405351.html](url)

[https://www.4shared.com/video/BJTWrqRnca/VID_20180307_1409271.html](url)

[https://www.4shared.com/video/0bCfK8Fsca/VID_20180307_1411281.html](url)

**Comment by thaliel** [comment] 2018-03-08 03:52
too big *screams into the void*

**Comment by cpriest** [comment] 2018-03-08 03:54
Okay, well... hmm.  What exact browser version are you using?  Perhaps I can reproduce with that information.  This happens even with a new, clean profile?

**Comment by thaliel** [comment] 2018-03-08 04:02
it does. I switched to my addon-less test profile and installed the beta on it. Same behaviour.

**Comment by cpriest** [comment] 2018-03-09 13:55
Can you describe the behavior that it does without SnapLinks installed?  Based on your original description I'm not finding any difference in behavior.

**Comment by thaliel** [comment] 2018-03-09 14:34
without the beta (3.1.1.3  works just fine), tabs will always work gthe same as they do without the addon: switch to the next tab to the right when one tab is closed. Only the beta version will take me back to the leftmost tab upon closing

**Comment by cpriest** [comment] 2018-03-09 20:49
Okay, I've finally reproduced what you're seeing.  This only happens under certain circumstances.

It seems to happen if you are closing the tab next to the opening tab and only if you have not moved between several of the tabs first.  I'll see if I can find a workaround for the issue.

**Comment by thaliel** [comment] 2018-03-09 20:59
good to know I wasn't paranoid after all. Keep up the good work

**Comment by cpriest** [comment] 2018-03-12 13:32
Okay, I've figured out what is causing this and that the behavior is what FireFox intended, but it is configurable.

It has to do with setting the openerTabId when creating the new tab (which is required for Tree Style Tabs #30).

I do not know if I can get a web extension to modify an about:config parameter, but you can certainly do so by going to about:config in the URL bar and search for a property named browser.tabs.selectOwnerOnClose and set it to false. 

I'll close this ticket and open a new feature request to add an option to set that flag from the options panel.

**Closed by cpriest** 2018-03-12 13:32 UTC

**Comment by cpriest** [comment] 2018-03-17 17:37
have you tried that setting change and found it took care of it for you?
