### ISSUE TITLE
Some links fail to be recognized on feedly.com

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#160] opened 2017-01-25 14:41 UTC
## Steps to reproduce
1. Visit http://feedly.com/ and create a Feedly account
2. Visit http://feedly.com/i/subscription/feed/http://safebooru.org/index.php?page=atom
3. Change the feed view to "title-only" by clicking the arrow next to the feed name
4. Draw a rectangle around some links with Snap Links

## Expected result
All relevant feed links get selected

## Actual result
Certain (random?) links fail to get selected (see below). You may have to scroll down and try other links to see the problem. Holding down Alt while dragging doesn't make a difference

![firefox_2017-01-25_06-33-09](https://cloud.githubusercontent.com/assets/5490615/22294578/a3454b38-e2c8-11e6-8512-2dae3e3297c2.png)

**Comment by cpriest** [comment] 2017-01-25 23:25
Strange...  I'll look into it when I get a chance.

**Comment by cpriest** [comment] 2017-10-29 17:17
Hey Keith, I could not get your feed to show up, but I created a test feed and added some sources to it, switched to title-only mode and could not reproduce.  I am running the latest master, so it could be that this is fixed now.

If you run into this again, please re-open.  Something that can help for pages that are experiencing a problem but I can't get to is to save the web page (complete) and post it here, then I can download it and use it for testing. 

I'm going to close this for now, feel free to re-open if the next beta release still shows a problem.  Thanks for the report!

**Closed by cpriest** 2017-10-29 17:17 UTC
Labels: bug

**Comment by cpriest** [comment] 2018-03-06 12:17
Just thought I'd post that the FireFox beta has been released and is ready for updating, see https://github.com/cpriest/SnapLinksPlus.
