### ISSUE TITLE
Issues with running as a content script

### ISSUE THREAD

**Issue by blackwind** [cpriest/SnapLinksPlus#91] opened 2016-05-05 23:39 UTC
Two problems I found with Snap Links (v3) running as a content script:

* For better or worse, the selector box grows with page zoom. I say for worse.
* The selector box is affected by the page's CSS. A global `transition-duration` as I use on [my site](http://blackwind.org/) is particularly problematic.

**Comment by cpriest** [comment] 2016-05-06 01:21
Thank you, I had forgotten about those previous issues, I'll be sure to get them fixed.

**Comment by cpriest** [comment] 2016-07-19 19:59
Hey @blackwind, I had previously looked into this and noticed an issue which is now fixed (latest commit), but now that I'm re-reading your issue, I'm not sure I understand what you mean.

> For better or worse, the selector box grows with page zoom. I say for worse.
Are you saying the box grows (and no longer matches the cursor position after the page zoom?)

> The selector box is affected by the page's CSS. A global transition-duration as I use on my site is particularly problematic.
This is also fixed in the latest commit, I'm afraid there will be plenty of these kinds of issues with it being a Web Extension (since it's basically loading my code into your page), but this was bad enough to over-ride it.

**Comment by blackwind** [comment] 2016-07-19 21:52
> Are you saying the box grows (and no longer matches the cursor position after the page zoom?)

In short, with SL2, whether the page zoom is 10% or 1000%, the border width of the selector box is always consistent; with SL3, it could be 1px or 15px wide depending on your zoom.

> This is also fixed in the latest commit, I'm afraid there will be plenty of these kinds of issues with it being a Web Extension (since it's basically loading my code into your page), but this was bad enough to over-ride it.

Cheers!

Perhaps it would be wise to create an empty page in the background once at startup (I'm sure there's a WebExtension API for that), do `window.getComputedStyle(document.getElementsByTagName("html")[0]);` on it, and apply each default attribute to the selector box as `!important`?

**Comment by cpriest** [comment] 2016-07-20 02:15
> In short, with SL2, whether the page zoom is 10% or 1000%, the border width of the selector box is always consistent; with SL3, it could be 1px or 15px wide depending on your zoom.

I understand now, yes with SL2 (the most recent version) it was using XUL elements, technically outside of the page document, not possible with SL3.

I'll look at finding a way to deal with this issue with the next release.

> Perhaps it would be wise to create an empty page in the background once at startup (I'm sure there's a WebExtension API for that), do window.getComputedStyle(document.getElementsByTagName("html")[0]); on it, and apply each default attribute to the selector box as !important?

That would be pretty gratuitous, not likely very necessary either, most attributes won't have a problem really but it does bring to mind some that may be.

**Comment by cpriest** [comment] 2016-09-28 21:44
I'm going to close this issue as the issue is addressed in dev.  If you want to open a feature request for the zoom-factor issue I can mark it down as an enhancement request.  I don't know of a way off-hand to do this.

**Closed by cpriest** 2016-09-28 21:44 UTC
Labels: bug
