### ISSUE TITLE
Breaks spellcheck correction

### ISSUE THREAD

**Issue by perryjp** [cpriest/SnapLinksPlus#64] opened 2015-02-18 20:12 UTC
Plugin Version: 2.4.2
FF Version: 35.0.1
Platform: Ubuntu 14.04

After installing this plugin, when spellcheck detects an error and has right-click replace options, selecting one of those options fails to replace the word. Right clicking on the word again shows the replacement options duplicated each time a replacement is selected.

The issue goes away after disabling the plugin and restarting firefox.

Thanks

**Comment by cpriest** [comment] 2015-02-19 14:47
There have been other reports from users regarding similar problems and 
they have found them to be related to other plugins, take a look through 
the few closed tickets, there should be one or two related.

Thanks,

-Clint

**Comment by SvenPM** [comment] 2015-03-14 12:00
I ran into this issue as well, in with the current version Pale Moon 25.2 on Trusty (after fixing chrome.manifest to use the correct overlay). 

Steps to reproduce:
* set SL+ to use the RMB without modifier
* open a text box (like pastebin) and enter a misspelled word => each time you open the context menu you get another copy of the suggestions plus another copy of the dictionaries (in my case through hunspell)
* now set SL+ to use MMB or Shift+RMB
* try the same => no issue.
That was reproducible in two different profiles (one of them blank). Next I installed SL+ into a blank profile of FX 28 (sorry, have no later version, using it just for texting) the result was slightly different but also pretty much borked and again it could be fixed by linking SL*+ to something else than RMB. I haven't tried it on Windows.

Looks like binding SL+ to the same button as the context menu seems to be a bad idea.

**Comment by cpriest** [comment] 2015-03-14 22:53
Hmm, that's interesting, I can check into that.  I do suppress the right 
click menu until the mouse up event (and if SL+ has not been activated 
due to cursor position distance) then I make the menu popup, perhaps I'm 
causing FF to add it's language suggestions twice...

**Comment by SvenPM** [comment] 2015-03-15 11:54
If you cannot reproduce, there is also the chance that it could be related to the OS, in this thread we are both on Ubuntu 14.04 (Trusty), unfortunately, in the issue reported in 2013
https://github.com/cpriest/SnapLinksPlus/issues/16
the OP doesn't mention the OS.

**Comment by crisalis** [comment] 2015-03-24 14:20
I confirm this issue on Linux Mint 17.1. It's exactly as perryjp explains.
This has never happened to me on Windows 7 or 8/8.1, where I also have multiple languages for spellcheking.

**Comment by SvenPM** [comment] 2015-03-24 18:44
That's funny, so it's a Linux issue. Since Rebecca is also based on Trusty, it would be interesting to know, if it happens on distros that are not based on Trusty/Ubuntu/Debian. Where are the Arch guys when you need one?

**Comment by MarcoFalke** [comment] 2015-06-28 12:35
Confirmed with fedora.

**Comment by dyskette** [comment] 2015-07-04 15:56
Same, can confirm on Fedora 22, Firefox 41 (downloaded from Mozilla) and Firefox 39 (from repositories). Activating SHIFT, is a workaround at the moment.

**Comment by cpriest** [comment] 2016-04-30 10:46
This is probably not something I can do anything about.  SLP only suppresses the context menu until the RMB is released.  In any case, v3 is now being worked on, if this is still an issue with v3 please re-open.

**Closed by cpriest** 2016-04-30 10:46 UTC
