### ISSUE TITLE
Open links in order selected via drag

### ISSUE THREAD

**Issue by cpriest** [cpriest/SnapLinksPlus#40] opened 2014-03-30 09:18 UTC
https://addons.mozilla.org/addon/SnapLinksPlus/reviews/568326/reply

A user has left a review for your add-on, Snap Links Plus.

Rating:
4 out of 5 stars

Review:
Multi Links, dead since 2011, is an extension that did what this does, except would open links in the order you dragged them, so you could go right to left, and the first opened tab would contain the rightmost link, because you dragged over it first. This is the only flaw of this extension, as far as I can see. Adding this ability, at least as a toggle, would make it perfect for me.

https://app.leanboard.io/board/c29e6bcc-1437-486b-a4aa-dfed2de11d4d

**Comment by Keith94** [comment] 2016-12-05 16:29
I noticed this too, links selected from top to bottom always seem to get opened in _reverse_ order. It's somewhat confusing behavior to have it like that, and could affect workflow.

**Comment by cpriest** [comment] 2017-03-22 16:43
That's strange (sorry didn't see your response)... it should always be opened in document order, but perhaps it's doing that (while always inserting it one to the right of the current tab, which would reverse the order).

**Comment by remi-garcia** [comment] 2019-08-24 08:58
Duplicate of #291 and #239 . The latter should be kept. This one can be closed

**Closed** 2022-01-05 12:54 UTC
Labels: enhancement
