### ISSUE TITLE
Tabs open in reverse order (noticable when using delay)

### ISSUE THREAD

**Issue by RlctntFr** [cpriest/SnapLinksPlus#291] opened 2019-07-23 13:35 UTC
In version 3.1.7 the tabs open in reverse order, but each tab is inserted to the left of the previous one. For instance if you open 5 tabs they open like this:

5
4 5
3 4 5
2 3 4 5
1 2 3 4 5

They end up in the correct order, but this becomes a problem if you want to use a delay and browse the tabs while they're still opening. You either have to view them in reverse order or else wait until the whole set is open before viewing.

The "Open tabs at end of tab bar" setting has no affect on this behavior as that setting only appears to affect the group as a whole and not the individual tabs (which is fine.) The opening process is also not affected by switching tabs, it does the same thing regardless of whether you stay on the initial tab, switch to another one, or even close tabs while the group is still opening (this is also fine, and expected.)

The _only_ problem is that the tabs open in reverse order, with each tab inserted to the left. I would expect the exact opposite: tabs opening in sequential order, with each tab inserted to the right, which would of course look like this:

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5

**Comment by remi-garcia** [comment] 2019-08-24 08:58
Duplicate of #40 and #239 . The latter should be kept. This one can be closed

**Comment by RlctntFr** [comment] 2019-08-25 16:22
I disagree that this is a duplicate of either of those as this has nothing to do with drag direction. This is to do with links opening in the opposite order than expected regardless of drag direction. Even if #239 were to be implemented it's possible this issue would not be fixed, thus is should be handled as a different issue.

**Comment by remi-garcia** [comment] 2019-08-27 18:14
I meant that if #239 is fixed this is too

**Closed** 2022-01-05 12:41 UTC
