### ISSUE TITLE
Does nothing when Gesturefy addon is enabled

### ISSUE THREAD

**Issue by ClefAria** [cpriest/SnapLinksPlus#203] opened 2017-11-24 18:26 UTC
With the old addon, I had it only work when you held down a button with it. Maybe when that feature is added back in, it won't conflict with gestures anymore, but as it is now, dragging with right-click creates a rectangle that grabs no links, regardless of what I drag it over, when I have Gesturefy enabled.

**Comment by cpriest** [comment] 2017-11-26 01:15
Duplicate of #189

**Closed by cpriest** 2017-11-26 01:15 UTC
