### ISSUE TITLE
Bug/Feature Request: Pressing middlemouse button with middleclick and not dragging stops mouse from starting autoscroll

### ISSUE THREAD

**Issue by Sand-Mage** [cpriest/SnapLinksPlus#496] opened 2024-09-22 15:34 UTC
Pressing middle click with middle mouse button settings on snaplinks causes the middle mouse button to not function normally with the activation settings up to drag for a certain amount of pixels before activation. This disables auto scroll activation which would be indicated using a symbol like this: 
![a3c43d7f-e50d-4b34-bf28-751fd947bf94](https://github.com/user-attachments/assets/1c909263-3bce-4276-8c99-374be1ffe205)
To recreate: any of the past three version of snaplinks: set settings to activate on drag and then simply press middle mouse button. 
result:
Mouse does nothing.
expected result: 
mouse enters autoscrolling, changes to autoscrolling icon. 

If we could access the middle mouse button with middle mouse setting on it would effectively fix the newest bug as the browser would be doing the scrolling not the extension?

so the Feature request would be a setting that allows us to use both the middle click setting and have a toggle button in the gui for the scroll option

**Comment by cpriest** [comment] 2024-09-23 11:45
Duplicate of #495

**Closed by cpriest** 2024-09-23 11:45 UTC
