### ISSUE TITLE
Right clicking broken on YouTube

### ISSUE THREAD

**Issue by selimsum** [cpriest/SnapLinksPlus#472] opened 2024-04-17 17:34 UTC
Right clicking (without dragging) anywhere on youtube.com randomly clicks somewhere on the page that the cursor is not pointing at. Single or multiple unwanted tabs are opened as a consequence.

This has been happening for a week or so. I can't reproduce this on any other websites, it's just YouTube.

My settings:
Select elements when I hold down: **No modifier** and I **right click** and drag for **5 pixels**

Browser: Firefox Nightly 127

**Comment by cpriest** [comment] 2024-04-17 17:57
Is this on Linux?  I just tested w/ Windows on FF/125 and it works as expected.

**Comment by selimsumlu** [comment] 2024-05-04 21:28
I've also noticed an additional blank tab with this URL:
moz-extension://facfe2ca-c8b4-4bc1-a6d2-f36595f30421/_generated_background_page.html

**Comment by kaisersoze80** [comment] 2024-05-18 06:52
Problem seems to be related to the body of the page having 0 as height in CSS.

As a work-around I temporarily solved it by forcing `body { height: 1000px; }`.

I accomplished that by using Stylus firefox extension.

Hope this can help devs to found the reason of the issue and fix it.

**Comment by erik7777** [comment] 2024-05-22 16:26
As mentioned, this just started happening with Youtube with the SnapLinksPlus Extension Active.  The Conflict makes Youtube basically unusable without deactivating the Extension.

**Comment by cpriest** [comment] 2024-05-22 20:25
This is on www.youtube.com?  I'm using FF 127 (Developer version) and it works just fine in a private window with just snaplinks enabled for private windows (on Windows 11).

**Comment by selimsumlu** [comment] 2024-05-22 20:33
> This is on [www.youtube.com](http://www.youtube.com)? I'm using FF 127 (Developer version) and it works just fine in a private window with just snaplinks enabled for private windows (on Windows 11).

Correct, this only happens on www.youtube.com. I can still reproduce it on Firefox 128 (Nightly) on Windows 11.

**Comment by cpriest** [comment] 2024-05-22 21:28
OK, I will watch when FF129 comes to the Developer channel and see what's going on.

**Comment by selimsumlu** [comment] 2024-05-22 21:45
I've just tested with the latest Developer Edition (127.0b5) and made a recording to make sure we're on the same page.

This is a fresh installation. I haven't logged in to YouTube and only installed SnapLinksPlus. I've **right clicked** on video thumbnails on this recording.

https://github.com/cpriest/SnapLinksPlus/assets/1046789/4262d0e0-137e-4aa5-9967-1c6b6c2f09a9

**Comment by cpriest** [comment] 2024-05-22 22:11
Thanks for that video, that helps a lot to see what's going on,
    though I am not able to reproduce the issue.
    
    I only quickly tested with my main profile, I will start a fresh
    profile with just SnapLinks and see what I get shortly.

**Comment by erik7777** [comment] 2024-05-23 06:55
Hello, I am on Windows 11 with Firefox 126.0 (64 Bit).  The Youtube Issue started after updating to Firefox 126.

Pressing Right Click on Youtube with SnapLinks Active does not produce the Right Click Menu, and instead opens multiple links instead.

Thanks for checking!

**Comment by cjdjkobe** [comment] 2024-05-31 23:26
I, too, am having this issue, but to add to a note that might help with troubleshooting: shift-clicking will just open the regular rmb-window on both video and page.  Does not return the lasso functionality, however.

Windows 10, 126.0 Firefox

**Comment by barbaduk** [comment] 2024-06-02 17:16
> Thanks for that video, that helps a lot to see what's going on, though I am not able to reproduce the issue. I only quickly tested with my main profile, I will start a fresh profile with just SnapLinks and see what I get shortly.

Try it on 130% page scale (or maybe it's different for you)
For me it works fine on 90%, 120%, 126%, but breaks at 100%, 110% 130%

**Comment by cjdjkobe** [comment] 2024-06-02 18:50
> Try it on 130% page scale (or maybe it's different for you) For me it works fine on 90%, 120%, 126%, but breaks at 100%, 110% 130%

Strangely, 130% works for me too.

**Comment by erik7777** [comment] 2024-06-02 22:32
I did not scale to 130%, but it works again for me too.

Since there was no Snaplinks update, Youtube must have corrected the problem.

**Comment by Parsnip** [comment] 2024-06-02 22:36
Still broken here, so I did some testing.

Just to confirm here as well, on my end right click is broken on normal 100% FF zoom, but works just fine on 70%, 110% and 120% zoom levels for example. It's really unusual behavior.

It doesn't seem to be directly connected to window size, since it occurs fullscreen and windowed Firefox.

Since the results seem to vary between people, my first thought is that it's somehow connected to screen resolution and Windows scale values not playing nice with FF scale values.
Some quick testing seems to suggest that any (up to 4K at least) display resolution combined with Windows scaling set to 100% and Firefox scaling set to 100% and everything works as expected.
Testing a bit more, on a 4K display resolution, keeping the FF scaling at the default 100%, and then going up the Windows scale in increments of 25%, things break the first time at Windows scale 200%.

So, who's good at math? 😄

**Comment by erik7777** [comment] 2024-06-03 06:21
I just checked again.  The reason it started working for me was because I added a Second Monitor.

With Extended Display, everything works fine.  With Duplicate Monitors, everything is still broken, regardless of the Resolution.  I did not change scale settings.

**Comment by blaharginhoogin** [comment] 2024-06-20 01:52
I can add some details to this SnapLinks - Youtube issue.!


If Youtube is open in Firefox maximized = issue persists.

If Youtube is open, but _not_ maximized = the issue is gone!

Also, it seems the File Menu has to be visible in the browser.


Hopefully someone smarter than myself can use these details to figure out the issue.

Windows 10
Firefox
SnapLinks: hold right lick+drag

**Comment by cjdjkobe** [comment] 2024-06-25 19:37
I've noticed this issue cropping up when you open a .jpg or other image from certain sites (but not all jpegs??), expand it to full size, then right click on it.

For instance, [Instagram images](https://instagram.fosu2-2.fna.fbcdn.net/v/t51.29350-15/448920033_2662459947246568_8223076744516704134_n.heic?stp=dst-jpg_e35&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xNDQweDE0NDAuc2RyLmYyOTM1MCJ9&_nc_ht=instagram.fosu2-2.fna.fbcdn.net&_nc_cat=104&_nc_ohc=FZSG8Ds25oMQ7kNvgGmAyoH&edm=AEhyXUkBAAAA&ccb=7-5&ig_cache_key=MzM5Njg1OTgwOTQwMTAzMDcyMw%3D%3D.2-ccb7-5&oh=00_AYARUycnQZNOW4dSeSZa-uszG5qwR-sW827LE38OatrCyQ&oe=6680EB49&_nc_sid=8f1549)

**Comment by Parsnip** [comment] 2024-07-09 19:13
I noticed that the height: 1000px workaround messes up youtube embeds in (some?) other sites since the stylus is applied on the iframe embed as well.
So I changed the snaplinks activation button to mouse3 instead of right click for now as another workaround.

**Comment by cpriest** [comment] 2024-07-19 00:23
Do you have a URL where I can see this
      happening?

**Comment by anotatta** [comment] 2024-08-26 07:18
Still broken.  On youtube, Zoom level greater than 95% is the sweet spot for me.
If the site blacklist feature ( Feature Request: Blacklist #473 ) is implemented, then that would be a good workaround.

**Comment by cpriest** [comment] 2024-09-11 12:40
v3.1.12 is pending review and should be available very soon.

**Comment by erik7777** [comment] 2024-09-11 19:00
Thanks!

**Comment by erik7777** [comment] 2024-09-17 04:33
Looks like the Problem with Youtube has been fixed with the Snaplinks Update.

Thanks!

**Comment by Sand-Mage** [comment] 2024-09-17 05:38
The scrolling isnt working on other sites now though it seems

**Comment by Sand-Mage** [comment] 2024-09-17 05:43
Update and clarification:  While holding middle mouse I cannot auto scroll down, only up works on sites other than youtube. Youtube is working fine.

**Comment by Sand-Mage** [comment] 2024-09-17 16:59
https://github.com/user-attachments/assets/71ec0b6f-8b81-40ad-bfe0-f4eda427bf66

**Closed** 2024-09-22 13:46 UTC
Labels: awaiting release
