### ISSUE TITLE
Change the right click behvior

### ISSUE THREAD

**Issue by egozi44** [cpriest/SnapLinksPlus#278] opened 2019-04-28 10:12 UTC
So I really liked that addon Multi links plus which is no longer being support with FF,

SnapLinksPlus seem to be the only successor for it, so far I found only one thing that bothers me though, I set the hotkeys so I will need to hold shift and right click as I select some links (like what I had in Multi links)

However even while it does the work, it still keep open the normal right click selection box menu you have regardless of the add-on, can you change it?

Also will be nice if you can add warning for open more than 40 links together (one that ask you if you sure you want to open so many) like Multi links plus had if haven;t already, 

Thx

**Comment by cpriest** [comment] 2019-04-28 16:34
I'm assuming you're running this on some *nix variant?  This happens because Firefox opens the context menu on mouse down rather than on mouse up as it does on Windows (and Mac I think).

If that's the case, this is a duplicate of ticket #243.

If you could open a new ticket for your feature request, I would appreciate it.  If this isn't the same as #243, please re-open the ticket.

**Closed by cpriest** 2019-04-28 16:34 UTC

**Comment by egozi44** [comment] 2019-04-29 12:44
I uses win7 sp1 and I actually tested it with tor browser xP

**Comment by cpriest** [comment] 2019-04-30 11:52
Hmm, can you try and reproduce the issue with standard Firefox?

**Comment by egozi44** [comment] 2019-05-01 13:45
Will do but on my main machine I still use old FF with multi links plus add-on instead, one of the reasons I test addons on other FF's based browser is because I want to move from pre quantum FF ver to the new one but don't want to lose some of my addons which haven't and won't be update for quantum versions, Multi links was one of them, so finding snap link really gave me hopes,

I heard it should be possible to run two ver of Old and new FF without make them collide with each other, but I still need to look into it
