### ISSUE TITLE
Twitter status not detected as a link

### ISSUE THREAD

**Issue by Keith94** [cpriest/SnapLinksPlus#170] opened 2017-04-24 16:02 UTC
Page: http://www.allgamesdelta.net/2017/04/bayonetta-pc-port-gets-updated-with.html

Screenshot:

![firefox_2017-04-24_08-55-49](https://cloud.githubusercontent.com/assets/5490615/25346261/ff98d686-28cb-11e7-9ccc-1fd9f0027e70.png)

Btw, is the project still alive?

**Comment by cpriest** [comment] 2017-04-25 23:39
It is, I just have my limited time focused elsewhere at the moment.  Also waiting for the new plugin api to mature a bit more.

As for this bug report, that is a peculiar one.  I don't see anything on the surface that should be causing it to fail.  It's an <A> element with a <SPAN> in it.  Both are absolutely positioned though which may be causing a problem.  

I'll look into this when I get back to this project.  Thanks for the report.

**Comment by cpriest** [comment] 2017-10-29 12:06
I've looked into this issue further @Keith94.  In FF this is being loaded in an IFRAME, this shouldn't be a problem as the script is now configured to load into all frames, but is still not being loaded into the IFRAME.  I will need to see what Mozilla says about it, I couldn't find any bug reports about issues with IFRAMES.

In Chrome it's a different story (probably easier in the end to fix, though not sure without doing it).  There twitter is using a custom web component with a #shadowRoot document.  I'm not certain of the security implications of this but it's not an IFRAME.  In any case that is a separate issue.

Unfortunately it would appear this issue is not going to be able to be fixed by the next beta release.  I'll circle back here once I knock out some of the other issues.

**Comment by remi-garcia** [comment] 2019-09-08 07:25
Can't reproduce this but #232 states the problem and gives an example we can work with. This one can be close as a duplicate.

**Closed** 2019-09-08 15:52 UTC
Labels: bug, help wanted
