### ISSUE TITLE
Javascript context menus on some pages no more working with SnapLinksPlus enabled

### ISSUE THREAD

**Issue by nturcot** [cpriest/SnapLinksPlus#155] opened 2016-12-21 12:02 UTC
Hello,

Some pages override the context (right-click) menu of the browser to display an alternate menu, such as Google Maps or Zimbra webmail. It seems that when Snap Links Plus 3.1.1.3 is enabled, these menus don't open any more.

Steps to reproduce:
1. Disable Snap Links Plus
2. Open https://www.google.com/maps and wait for the page to fully load.
3. Right-click somewhere on the map: a context menu pops up, offering options such as "Directions", "Measure distance"...
4. Enable Snap Links Plus
5. Reload the Google Maps tab, right-click on the map: nothing happens.

**Comment by cpriest** [comment] 2016-12-21 12:50
I have confirmed I can see the issue.  This has to do with the mouse down handling and relates to another ticket with a similar effect.  I do not yet know how to get around this issue but I will look for a solution.  Most websites fire on the mouse up event, it looks like google maps does it on the mouse down (which SLP suppresses until it knows a drag is not happening).

**Comment by cpriest** [comment] 2019-04-28 17:27
This should be fixed in the next v3.1.6 release, if not, please re-open.

**Closed by cpriest** 2019-04-28 17:27 UTC
Labels: bug
